package hu.nem3d.zincity;


//list the tiles on the texture png in their respective order.
public enum TextureTiles {
    GRASS,
    WATER,
    FOREST_SPARSE,
    FOREST_DENSE,
    ROAD,
    HOUSE_SMALL,
    HOUSE_MEDIUM,
    HOUSE_LARGE,
    INDUSTRY_SMALL,
    INDUSTRY_MEDIUM,
    INDUSTRY_LARGE,
    SERVICE_SMALL,
    SERVICE_MEDIUM,
    SERVICE_LARGE,
    POLICE_STATION,
    FIRE_STATION,
    ARENA_NORTHWEST,
    ARENA_NORTHEAST,
    ARENA_SOUTHWEST,
    ARENA_SOUTHEAST,
    POWER_PLANT_NORTHWEST,
    POWER_PLANT_NORTHEAST,
    POWER_PLANT_SOUTHEAST,
    POWER_PLANT_SOUTHWEST
}
